Hw07
justfallingup/gocore pull request #2
Opened 2021-06-05 07:49 UTC by justfallingup

коммит с code review и переписанный код

2021-06-05 14:27 UTC, DmitriyVTitov requested changes
Слишком круто :)

2021-06-05 14:27 UTC, DmitriyVTitov commented on hw07/geom.go
> +	"errors"
вот этот пакет уже настораживает :)

2021-06-05 14:27 UTC, DmitriyVTitov commented on hw07/geom.go
> +}
тип экспортируется, а его поля - нет.
и как им пользоваться из внешнего пакета?

2021-06-05 14:27 UTC, DmitriyVTitov commented on hw07/geom.go
> +}
а, вот как!
это ну яяяяяяяяяяяяяяяяяаааааааааааавный перебор для простой функции из одной строчки

2021-06-05 14:27 UTC, DmitriyVTitov commented on hw07/geom.go
> +	d := math.Sqrt(math.Pow(g.x2 - g.x1, 2) + math.Pow(g.y2 - g.y1, 2))
смысл в переменной `d`?

2021-06-06 18:29 UTC, justfallingup commented on hw07/geom.go
> +	d := math.Sqrt(math.Pow(g.x2 - g.x1, 2) + math.Pow(g.y2 - g.y1, 2))
нету его:)

2021-06-06 18:30 UTC, justfallingup commented on hw07/geom.go
> +}
ок тогда делаю метод который валидирует Geom и он даже не использует пакет errors:)

2021-06-06 18:31 UTC, justfallingup commented
> это документация к пакету, а не комментарий к функции
тогда у документации к пакету странное расположение!

2021-06-08 18:09 UTC, DmitriyVTitov approved these changes
Будем считать, что разобрались. Мне не всё нравится, в комментариях указал.

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom.go
> +//Distance вычисляет расстояние между точками, чьи координаты в Geom
пробел после `//`

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom.go
> +//Distance вычисляет расстояние между точками, чьи координаты в Geom
и точка в конце

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom.go
> +}
вот это никакого отношения к вычислению расстояния не имеет, этому не место в пакете

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom.go
> +}
этот тип тоже совершенно лишний

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom.go
> +func (g *Geom) Distance() float64 {
Опасайтесь функций без аргументов!
Вместо метода, которым не понятно как пользоваться, лучше сделать простую функцию с аргументами.
`func Distance(x1, x2, y1, y2 float64) float64`

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom_test.go
> +			}
вон какой сложный тест получается!

2021-06-08 18:09 UTC, DmitriyVTitov commented on hw07/geom_test.go
> +}
в пакете полезного кода - 1 строка
тест - 90 строчек

2021-06-24 09:50 UTC, justfallingup commented on hw07/geom.go
> +}
получается тут я пытаюсь думать за пользователя, какие у него координаты будут пусть сам решит, это не дело пакета

2021-06-24 09:50 UTC, justfallingup commented on hw07/geom.go
> +func (g *Geom) Distance() float64 {
поправлено, теперь просто функция

2021-06-24 09:50 UTC, merged